name: threshold
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - threshold.mo
      - Makefile
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/threshold.yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  threshold-darwin:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Threshold Darwin
        run: |
          dfx start --background
          make test self-upgrade
  threshold-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Threshold Linux
        run: |
          dfx start --background
          make test self-upgrade
